name: DroneSwarm Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DroneSwarm
        uses: actions/checkout@v4
        with:
          path: DroneSwarm

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support kpartx wget unzip

      - name: Run Build Script
        run: |
          sudo bash DroneSwarm/builder/build.sh
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: clover-droneswarm-native
          path: images/*.img
